### ISSUE TITLE
svc hesabıma gelmiyor ?

### ISSUE THREAD

**Issue by Anays33** [LinkNotZelda8/SavulCoin#4] opened 2021-01-24 18:45 UTC
2021-01-24T16:38:23.990Z - info - mine-worker: Block found: time '0 sec' dif '9007199254740991' hash '04736f35f516d3cd9adf7f2f028aaf74e18d63efafd00963278e301931f06e20'

ilk açtığımda bulmuş fakat bana gelmedi ?

**Comment by LinkNotZelda8** [comment] 2021-01-25 00:17
Duplicate of #3 

Also please write better descriptions.

**Closed by LinkNotZelda8** 2021-01-25 00:17 UTC
